/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_chensiwen_edugame_JNIUtil.h"
/*
 * Class:     com_chensiwen_edugame_JNIUtil
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chensiwen_edugame_JNIUtil_getNativeString
  (JNIEnv * env, jobject obj)
{
    return env -> NewStringUTF("Hello world! from jni");
}

/*
 * Class:     com_chensiwen_edugame_JNIUtil
 * Method:    getNativeStringWithParam
 * Signature: (Ljava/lang/String;IJZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chensiwen_edugame_JNIUtil_getNativeStringWithParam
  (JNIEnv * env, jobject obj, jstring s, jint i, jlong l, jboolean b)

{
    return env -> NewStringUTF("Hello world! from jni with param");
}